config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'cards#home'

  resources :card_check, only: :create
  resources :cards
  resources :users

  resources :user_sessions, only: %i[new create destroy]

  get 'login' => 'user_sessions#new', as: :login
  delete 'logout' => 'user_sessions#destroy', as: :logout
end

app/models/application_record.rb
# frozen_string_literal: true

# Aplication Record
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
# frozen_string_literal: true

# Card
class Card < ApplicationRecord
  belongs_to :user

  validates :original_text, :translated_text, presence: true
  validates :original_text, :translated_text, length: { in: 1..128 }
  validate :validate_not_equal

  scope :overdue_time, -> { where('review_date <= ?', DateTime.now) }

  def self.random
    overdue_time.order('RANDOM()').take
  end

  def validate_not_equal
    return unless original_text && translated_text

    if original_text.downcase.strip == translated_text.downcase.strip
      errors.add(:original_text,
                 I18n.t('cards.errors.unique'))
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

# User
class User < ApplicationRecord
  authenticates_with_sorcery!
  has_many :cards, dependent: :destroy

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 8 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :require_login

  def not_authenticated
    redirect_to login_path, alert: t('user.please_login')
  end
end

app/controllers/card_check_controller.rb
# frozen_string_literal: true

# Card Check controller
class CardCheckController < ApplicationController
  def create
    if CardAnswerService.call(params[:card_id], params[:translated_text])
      flash[:info] = t('cards.right')
    else
      flash[:warning] = t('cards.incorrectly')
    end
    redirect_back(fallback_location: card_check_index_path)
  end
end

app/controllers/cards_controller.rb
# frozen_string_literal: true

# Cards controller
class CardsController < ApplicationController
  before_action :init_card, only: %i[show edit update destroy]

  def index
    @cards = current_user.cards.all
  end

  def home
    @card = current_user.cards.random
  end

  def show; end

  def new
    @card = current_user.cards.build
  end

  def create
    @card = CardCreateService.call(current_user, card_params)

    if @card.save
      redirect_to @card
      flash.now[:notice] = t('cards.notice.create')
    else
      render :new
      flash.now[:warning] = t('cards.errors.fail')
    end
  end

  def edit; end

  def update
    if @card.update(card_params)
      redirect_to @card
      flash.now[:notice] = t('cards.notice.update')
    else
      render :edit
      flash.now[:warning] = t('cards.notice.fail')
    end
  end

  def destroy
    @card.destroy
    redirect_to cards_path
    flash[:notice] = t('cards.notice.destroy')
  end

  private

  def init_card
    @card = current_user.cards.find_by(id: params[:id])
  end

  def card_params
    params.require(:card).permit(:original_text, :translated_text)
  end
end

app/controllers/user_sessions_controller.rb
# frozen_string_literal: true

# User Sessions controller
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to(@user, notice: t('user.login_success'))
    else
      flash.now[:warning] = t('user.login_unsuccess')
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:users, notice: t('user.logout'))
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Users controller
class UsersController < ApplicationController
  before_action :init_user, only: %i[show edit update]

  skip_before_action :require_login, only: %i[index new create]

  def index
    @users = User.all
  end

  def show; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      auto_login(@user)
      redirect_to @user, notice: t('user.created')
    else
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: t('user.updated')
    else
      render :edit
    end
  end

  private

  def init_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/wellcome_controller.rb
# frozen_string_literal: true

# Wellcome controller
class WellcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/cards/_form.html.slim
= simple_form_for @card, defaults: { wrapper_html: { class: 'flex flex-col' } } do |f|
    =f.input :original_text, label: t('card.original_text')
    =f.input :translated_text, label: t('card.translated_text') 
    =f.button :submit

app/views/cards/home.html.slim
div
   - if @card
     h2 =@card.original_text 
     =form_tag card_check_index_url(@card) do
       =hidden_field_tag(:card_id, @card.id)
       =text_field_tag :translated_text
       =submit_tag t('cards.send'), class: "btn btn-light"

app/views/cards/index.html.slim
section class='grid grid-cols-3 gap-10'
    - for card in @cards
        div class='p-4 border-black border-4 rounded'
            div class='flex justify-around'
               =link_to t('cards.edit'), edit_card_path(card)
               =link_to t('cards.destroy'), card_path(card), method: :delete, data: { confirm: "Are you sure?" }
            p #{t('cards.original_text')}: #{card.original_text}
            p #{t('cards.translated_text')}: #{card.translated_text}
            p #{t('cards.review_date') }: #{card.review_date.strftime('%d/%m/%Y')}

app/views/cards/show.html.slim
div class='p-4 border-black border-4 rounded'
   p #{t('cards.original_text')}: #{@card.original_text}
   p #{t('cards.translated_text')}: #{@card.translated_text}
   p #{t('cards.review_date') }: #{@card.review_date.strftime('%d/%m/%Y')}
   

app/views/layouts/application.html.slim
doctype html
html
  head
    title = t('home.title')
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', 'data-turbo-track': 'reload'
  
  body
    section id='container'
      header class='clearfix'
        h1 =t('home.title')
        ul class='navigation-links'
          li 
            a href=cards_path =t('all_cards') 
          li 
            a href=new_card_path =t('add_card')
          - if current_user
            li
              = link_to t('user.edit'), edit_user_path(current_user.id)
            li
              = link_to t('user.logut'), logout_path, method: :delete
          - else
            li
              = link_to t('user.register'), new_user_path
            li
              = link_to t('user.login'), :login

      section
        = yield
      div class='flex justify-end'
        - flash.each do |type, msg|
          = content_tag(:div, msg)

app/views/user_sessions/_form.html.slim
= form_tag user_sessions_path, method: :post do
   = label_tag      :email
   = text_field_tag :email
   = label_tag          :password
   = password_field_tag :password
   = submit_tag  t('user.login')
    

app/views/user_sessions/new.html.slim
= render 'form'

app/views/users/_form.html.slim
= simple_form_for @user, defaults: { wrapper_html: { class: 'flex flex-col' } } do |f|
    =f.input :email, label: 'email'
    =f.input :password, label: 'password'
    =f.input :password_confirmation, label: 'password_confirmation'
    =f.button :submit
    

app/views/users/edit.html.slim
= render 'form'

app/views/users/index.html.slim
section class='grid grid-cols-3 gap-10'
    - for user in @users
        div class='p-4 border-black border-4 rounded'
            div class='flex justify-around'
            p email: #{user.email}
            

app/views/users/new.html.slim
= render 'form'

app/views/users/show.html.slim
div class='p-4 border-black border-4 rounded'
   p email: #{@user.email}

   

app/views/wellcome/wellcome.html.slim
p[style='font-size: 22px;'] =t('home.welcome')